ignores:
  [
    "@types/eslint",
    "@types/lodash.clonedeep",
    "eslint-config-prettier",
    "prettier-eslint",
    "prettier-eslint-cli",
    "prettier-stylelint",
    "stylelint-config-prettier-scss",
    "stylelint-config-standard-scss",
  ]
skip-missing: true
