ignores:
  [
    "@eslint/*",
    "@stylistic/*",
    "@types/*",
    "@typescript-eslint/*",
    "eslint-*",
    "globals",
    "next",
    "postcss",
    "prettier",
    "stylelint-*",
    "tsconfig-*",
  ]
skip-missing: true
