ignores:
  [
    "@types/eslint",
    "eslint-config-prettier",
    "postcss",
    "stylelint-config-prettier-scss",
    "stylelint-config-standard-scss",
    "tsconfig-paths",
  ]
skip-missing: true
